service: braintree
frameworkVersion: ">=1.8.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  default_env: 'Sandbox'
  keys: ${file(token/development.yml):}

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment:
    ENV: ${opt:env, self:custom.default_env}
    MERCHANT_ID: ${opt:merchant_id, self:custom.keys.merchant_id }
    PUBLIC_KEY: ${opt:public_key, self:custom.keys.public_key}
    PRIVATE_KEY: ${opt:private_key, self:custom.keys.private_key}

functions:
  token:
    handler: token/index.handler
    events:
      - http: GET handler
