service: braintree
frameworkVersion: ">=1.8.0 <2.0.0"

custom:
  stage: ${opt:stage, self:provider.stage}
  default_env: 'Sandbox'

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment:
    ENV: ${opt:env, self:custom.default_env}
    MERCHANT_ID: ${opt:merchant_id}
    PUBLIC_KEY: ${opt:public_key}
    PRIVATE_KEY: ${opt:private_key}

functions:
  token:
    handler: token/index.handler
    events:
      - http:
          method: get
          path: braintree/token
          cors: true
